// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxH0jmOugGncK7aRY7ttSarKP_E4WO1uI',
    appId: '1:693411379918:web:56ca7dd1c51a2d11552e9f',
    messagingSenderId: '693411379918',
    projectId: 'fir-flutter-auth-32fac',
    authDomain: 'fir-flutter-auth-32fac.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-32fac.appspot.com',
    measurementId: 'G-7ZVH7CTRRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_UuUA6jWtnXiq15tpflf1GZ-IlMttIs',
    appId: '1:693411379918:android:bee78e5733396335552e9f',
    messagingSenderId: '693411379918',
    projectId: 'fir-flutter-auth-32fac',
    storageBucket: 'fir-flutter-auth-32fac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDueuDkIm4YiJylxZXS7Rt9Zup46kUN3AU',
    appId: '1:693411379918:ios:3a0bb7d18b98adaa552e9f',
    messagingSenderId: '693411379918',
    projectId: 'fir-flutter-auth-32fac',
    storageBucket: 'fir-flutter-auth-32fac.appspot.com',
    iosBundleId: 'com.example.hisaabkitaabMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDueuDkIm4YiJylxZXS7Rt9Zup46kUN3AU',
    appId: '1:693411379918:ios:3a0bb7d18b98adaa552e9f',
    messagingSenderId: '693411379918',
    projectId: 'fir-flutter-auth-32fac',
    storageBucket: 'fir-flutter-auth-32fac.appspot.com',
    iosBundleId: 'com.example.hisaabkitaabMain',
  );
}
